### ISSUE TITLE
运行脚本时模拟器停留在欢迎界面

### ISSUE THREAD

**Issue by betterli** [tingsu/Stoat#16]
使用avdmanager create指令照着readme生成的模拟器。
运行脚本时模拟器停留在欢迎界面，无法运行下去，生成的是一个空的模型，甚至多次运行后模拟器出现卡死现象，查我也没查出来。
具体截图下附，望告知应当如何处理。
![QQ图片20201024235106](https://user-images.githubusercontent.com/19490798/97086380-7f609780-1655-11eb-9fb3-731eda36a5e1.png)

**Comment by tingsu** [comment]
你好，

这个问题解决了吗？avdmanager create的command line是正确的，你可以给下你的command line吗？

**Comment by betterli** [comment]
你好，并没有，稍等一下，我重创建一下

**Comment by betterli** [comment]
[错误报告.zip](https://github.com/tingsu/Stoat/files/5468601/default.zip)
这是我的执行全流程，包含环境的确认以及用来测试的app文件夹。
万望您的帮助。

**Comment by betterli** [comment]
最后是手动关闭欢迎界面，然后在运行过程中不关闭模拟器。
