### ISSUE TITLE
Maximum Supported Android API Version

### ISSUE THREAD

**Issue by freddiewanah** [tingsu/Stoat#18]
Hi Ting, 

I'm trying to test some of the apps with Stoat. However, I noticed that Android-18 is too old that the apps can't be installed. I then switched to Android-30 where apps can be installed, but the program seems can do no actions on the emulator and just say goodbye. 

Therefore, I wonder what is the latest Android API that you know that can run the program?

Thanks in advance.

**Comment by tingsu** [comment]
Thanks for trying Stoat. As far as I know, Stoat can run on Android 7.1 at least. In principle, Stoat is not restricted to specific Android versions. Can you give me more info (e.g., the log outputs) if you still have this problem.

- Ting

**Comment by freddiewanah** [comment]
Hi,

Thanks for getting back to me. I managed to get it running on 8.1. Later versions seem to have some issues controlling the emulator.

Cheers
