### ISSUE TITLE
Is Stoat have an option to choose the stop number of Intereation?

### ISSUE THREAD

**Issue by tykuyh** [tingsu/Stoat#4]
I have tried Sotat in a physical machine with the command in the readme , and found Stoat doesn't stop.
So is Stoat would continue testing until I force close it, or it will get all the elements and stop when all the elements have been clicked?
And does Stoat have an option to choose the time or times that it can stop?
Hope for your answer!

**Comment by tykuyh** [comment]
呃 我还是用中文说一下吧…
配好环境后 用的是5.0的实体机，然后是直接是一个apk文件的测试
命令行执行的就是这句了：
ruby run_stoat_testing.rb --app_dir /home/XX/Bites.apk --avd_name testAVD_1 --real_device_serial xxxxxx --stoat_port 2000
但是测试一直在执行然后不停下来，是不是有什么选项能够设定比如说执行多久或者执行多少次就会停下来呢，还是说是他会先获取所有的元素，因为我看stoat把apk文件解包了，然后等所有的元素都被点过了才会停下来呢。
如果是后者的话，感觉测试进入了一个死循环，如果是前者的话，希望能够知道一下是怎样的输入能够让stoat停下来。
谢谢！

**Comment by tingsu** [comment]
谢谢你的关注, Stoat能支持限定测试时间.

方法1: 通过限定model construction time,以及mcmc sampling时间, 有这么两个选项: --model_time, --mcmc_time, 默认时间设置分别是 --model_time 1.2h --mcmc_time 2h

如果你想缩短测试时间, 可以这样改: --model_time 30m --mcmc_time 30m  , 即model construction执行30分钟, mcmc sampling时间也为 30分钟.

ruby run_stoat_testing.rb --app_dir /home/XX/Bites.apk --avd_name testAVD_1 --real_device_serial xxxxxx --stoat_port 2000 **--model_time 30m --mcmc_time 30m**

对于model construction阶段也可以设置event执行数目, 如

ruby run_stoat_testing.rb --app_dir /home/XX/Bites.apk --avd_name testAVD_1 --real_device_serial xxxxxx --stoat_port 2000 --model_time 1.2h --mcmc_time 2h **--max_event 3000**

方法二: 通过整体给timeout时间, 如 **timeout 2h** ruby run_stoat_testing.rb --app_dir /home/XX/Bites.apk --avd_name testAVD_1 --real_device_serial xxxxxx --stoat_port 2000

如果你想看到其他选项, 可以 ruby run_stoat_testing.rb --help
