### ISSUE TITLE
Cannot generate coverage. ec

### ISSUE THREAD

**Issue by wujia1010** [tingsu/Stoat#5]
When I run the tool, it can't generate coverage.ec files on the  emulator.
Remind “remote object '/mnt/sdcard/coverage.ec' does not exist”. What is the reason?

**Comment by wujia1010** [comment]
my environment is Android 4.4, running on Ubuntu 14.04.
command line is:
ruby /home/xx/Stoat-master/Stoat/bin/run_stoat_testing.rb --app_dir /home/xx/test-project/MultiSmsSender-master --avd_name testAVD_stoat --avd_port 5554 --stoat_port 2000 --project_type ant --model_time 2h --mcmc_time 1h

**Comment by tingsu** [comment]
Is your problem resolved?

**Comment by tingsu** [comment]
Since there are no replies, I closed this issue. If the problem appears again, please re-open this issue.
