### ISSUE TITLE
repetitive paths

### ISSUE THREAD

**Issue by TinRain** [tingsu/Stoat#6]
We know that Stoat doesn't run duplicate paths very much. What should I do to make Stoat run more repetitive paths(how to modify the code in MCMCSampler?)

**Comment by tingsu** [comment]
Hi TinRain, what do you mean by running duplicate paths and repetitive paths? Can you give more explanations?

**Comment by tingsu** [comment]
Since there are no replies, I closed this issue. If the problem appears again, please re-open this issue.
