### ISSUE TITLE
undefined method 'size' for nil:NilClass

### ISSUE THREAD

**Issue by claudiom4sir** [tingsu/Stoat#9]
Good morning Sir,

I'm trying to execute your tool but I have encountered a problem that I can't solve.
It seems like a file can't be created and for this reason a null pointer exception is thrown at line 391 in file rec.rb in a3e package.

I can't explain why it executes this line of code because, if that file doesn't exist, the system should exit with code 0 (line 385).

Could somebody help me?

Thanks in advance.

Here there is the output of the execution.
[output.txt](https://github.com/tingsu/Stoat/files/2983593/output.txt)

**Comment by tingsu** [comment]
Can you specify the project type, and try again?

sudo ruby run_stoat_testing.rb --app_dir ~/Desktop/Calendar_Notifications_v3.14.159.apk --avd_name 192.168.56.101 --avd_port 5555 --stoat_port 9009 **--project_type apk**

Another issue from your log seems the emulator does not successfully boot:

**sh: 1: emulator: not found**

Is the **emulator** command can be successfully called?

**Comment by claudiom4sir** [comment]
The command "emulator" works fine, but probably it can't find the attached devices. Instead, adb works properly and manages to find them.
However, i have tried to fix this problem by changing some lines of code and the emulator (I use GenyMotion) seems to work fine and I can see that the tool is able to open the application.
I have tried to add "--project_type apk" but nothing is changed.

**Comment by tingsu** [comment]
So was this problem solved? Stoat was run on genymotion at the initial stage of development. But we have not thoroughly test it on genymotion.

**Comment by claudiom4sir** [comment]
Unfortunately not. I think the problem is that Stoat doesn't manage to create the file `/home/sal/Desktop/Calendar_Notifications_v3.14.159-output/stoat_fsm_output/com.github.quarck.calnotify.ui.MainActivity_command.txt`

**Comment by tingsu** [comment]
Can you share your app file so that I can run on my side? Btw, have you tried other apps? Does Stoat also fail on other apps?

**Comment by claudiom4sir** [comment]
Yes, I have tried with another app obtaining the same result.
Below there is the app file.
[Calendar_Notifications_v3.14.159.apk.zip](https://github.com/tingsu/Stoat/files/2988597/Calendar_Notifications_v3.14.159.apk.zip)
